export interface JobRole {
  id: string;
  name: string;
  category: string;
  required_skills: string[];
  preferred_skills: string[];
  keywords: string[];
  minimum_years: number;
  scoring_weights: {
    skills: number;
    experience: number;
    projects: number;
    education: number;
    impact_metrics: number;
  };
  education_requirements: string[];
}

export const JOB_ROLES: JobRole[] = [
  // TECH
  {
    id: "data-scientist",
    name: "Data Scientist",
    category: "Tech",
    required_skills: ["Python", "SQL", "Statistics", "Machine Learning", "Data Analysis", "Pandas", "NumPy"],
    preferred_skills: ["TensorFlow", "PyTorch", "Tableau", "Power BI", "Spark", "R", "Deep Learning"],
    keywords: ["data-driven", "insights", "modeling", "analytics", "prediction", "hypothesis", "A/B testing"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "Master's in Data Science", "Statistics", "Mathematics"],
  },
  {
    id: "ml-engineer",
    name: "ML Engineer",
    category: "Tech",
    required_skills: ["Python", "TensorFlow", "PyTorch", "MLOps", "Docker", "SQL", "Machine Learning"],
    preferred_skills: ["Kubernetes", "AWS SageMaker", "MLflow", "Airflow", "Spark", "C++", "CUDA"],
    keywords: ["model deployment", "pipeline", "training", "inference", "optimization", "production ML"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "Master's in ML/AI", "Computer Engineering"],
  },
  {
    id: "ai-engineer",
    name: "AI Engineer",
    category: "Tech",
    required_skills: ["Python", "Deep Learning", "NLP", "Computer Vision", "TensorFlow", "PyTorch"],
    preferred_skills: ["Transformers", "LLMs", "Reinforcement Learning", "GANs", "ONNX", "Triton"],
    keywords: ["artificial intelligence", "neural network", "AI system", "foundation model", "fine-tuning"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Master's in AI", "PhD in CS", "Bachelor's in CS"],
  },
  {
    id: "backend-engineer",
    name: "Backend Engineer",
    category: "Tech",
    required_skills: ["Node.js", "Python", "SQL", "REST APIs", "Git", "Database Design"],
    preferred_skills: ["GraphQL", "Redis", "Docker", "Kubernetes", "AWS", "Microservices", "Go"],
    keywords: ["scalable", "API design", "server-side", "architecture", "performance", "database"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "Software Engineering"],
  },
  {
    id: "frontend-engineer",
    name: "Frontend Engineer",
    category: "Tech",
    required_skills: ["JavaScript", "TypeScript", "React", "HTML", "CSS", "Git"],
    preferred_skills: ["Next.js", "Vue.js", "Tailwind CSS", "Testing", "Webpack", "Performance Optimization"],
    keywords: ["responsive", "UI/UX", "component", "accessibility", "SPA", "web performance"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "Web Development"],
  },
  {
    id: "fullstack-developer",
    name: "Full Stack Developer",
    category: "Tech",
    required_skills: ["JavaScript", "TypeScript", "React", "Node.js", "SQL", "Git", "REST APIs"],
    preferred_skills: ["Next.js", "Docker", "AWS", "MongoDB", "GraphQL", "Redis"],
    keywords: ["full-stack", "end-to-end", "deployment", "frontend", "backend", "database"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "Software Engineering"],
  },
  {
    id: "devops-engineer",
    name: "DevOps Engineer",
    category: "Tech",
    required_skills: ["Docker", "Kubernetes", "CI/CD", "Linux", "AWS", "Terraform", "Git"],
    preferred_skills: ["Ansible", "Jenkins", "Prometheus", "Grafana", "GCP", "Azure"],
    keywords: ["infrastructure", "automation", "deployment", "monitoring", "pipeline", "cloud"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "IT", "Systems Engineering"],
  },
  {
    id: "cloud-engineer",
    name: "Cloud Engineer",
    category: "Tech",
    required_skills: ["AWS", "Azure", "GCP", "Terraform", "Docker", "Networking", "Linux"],
    preferred_skills: ["Kubernetes", "Serverless", "CloudFormation", "Security", "Cost Optimization"],
    keywords: ["cloud architecture", "migration", "scalability", "multi-cloud", "IaC"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "Cloud Certifications"],
  },
  {
    id: "cybersecurity-analyst",
    name: "Cybersecurity Analyst",
    category: "Tech",
    required_skills: ["Network Security", "SIEM", "Vulnerability Assessment", "Linux", "Python"],
    preferred_skills: ["Penetration Testing", "SOC", "Incident Response", "Compliance", "Forensics"],
    keywords: ["threat", "vulnerability", "security audit", "firewall", "encryption", "compliance"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Cybersecurity", "CS", "CISSP", "CEH"],
  },
  {
    id: "qa-engineer",
    name: "QA Engineer",
    category: "Tech",
    required_skills: ["Test Automation", "Selenium", "Jest", "API Testing", "SQL", "Git"],
    preferred_skills: ["Cypress", "Playwright", "Performance Testing", "CI/CD", "Python"],
    keywords: ["quality assurance", "testing", "bug", "regression", "test plan", "coverage"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "ISTQB"],
  },
  {
    id: "data-engineer",
    name: "Data Engineer",
    category: "Tech",
    required_skills: ["Python", "SQL", "ETL", "Spark", "Airflow", "Data Warehousing"],
    preferred_skills: ["Kafka", "dbt", "Snowflake", "BigQuery", "AWS Glue", "Databricks"],
    keywords: ["pipeline", "data lake", "warehouse", "batch processing", "streaming", "schema"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "Data Engineering"],
  },
  {
    id: "mlops-engineer",
    name: "MLOps Engineer",
    category: "Tech",
    required_skills: ["Python", "Docker", "Kubernetes", "MLflow", "CI/CD", "AWS/GCP"],
    preferred_skills: ["Kubeflow", "Terraform", "Monitoring", "Feature Store", "Model Registry"],
    keywords: ["model deployment", "ML pipeline", "monitoring", "reproducibility", "automation"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "ML/AI background"],
  },
  {
    id: "mobile-developer",
    name: "Mobile Developer",
    category: "Tech",
    required_skills: ["React Native", "Swift", "Kotlin", "REST APIs", "Git"],
    preferred_skills: ["Flutter", "Firebase", "App Store Deployment", "CI/CD", "Testing"],
    keywords: ["iOS", "Android", "mobile app", "responsive", "push notifications", "offline"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "Mobile Development"],
  },
  {
    id: "software-architect",
    name: "Software Architect",
    category: "Tech",
    required_skills: ["System Design", "Microservices", "Cloud Architecture", "Design Patterns", "SQL"],
    preferred_skills: ["Event-Driven Architecture", "Domain-Driven Design", "Kubernetes", "Security"],
    keywords: ["architecture", "scalability", "design decision", "trade-off", "technical leadership"],
    minimum_years: 7,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in CS", "Master's in CS"],
  },
  // BUSINESS
  {
    id: "product-manager",
    name: "Product Manager",
    category: "Business",
    required_skills: ["Product Strategy", "Roadmapping", "User Research", "Agile", "Data Analysis"],
    preferred_skills: ["SQL", "Figma", "A/B Testing", "Market Research", "Pricing Strategy"],
    keywords: ["product-market fit", "user needs", "KPI", "OKR", "stakeholder", "prioritization"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Business", "MBA", "CS"],
  },
  {
    id: "project-manager",
    name: "Project Manager",
    category: "Business",
    required_skills: ["Project Planning", "Agile", "Scrum", "Risk Management", "Stakeholder Management"],
    preferred_skills: ["Jira", "MS Project", "PMP", "Budget Management", "Confluence"],
    keywords: ["timeline", "milestone", "deliverable", "scope", "resource allocation", "sprint"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Business", "PMP Certification"],
  },
  {
    id: "business-analyst",
    name: "Business Analyst",
    category: "Business",
    required_skills: ["Requirements Gathering", "Data Analysis", "SQL", "Process Mapping", "Documentation"],
    preferred_skills: ["Tableau", "Power BI", "Jira", "UML", "Python"],
    keywords: ["business requirements", "stakeholder", "process improvement", "gap analysis", "ROI"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Business", "CS", "Economics"],
  },
  {
    id: "marketing-manager",
    name: "Marketing Manager",
    category: "Business",
    required_skills: ["Digital Marketing", "Content Strategy", "SEO", "Analytics", "Campaign Management"],
    preferred_skills: ["Google Ads", "Social Media", "Email Marketing", "CRM", "Marketing Automation"],
    keywords: ["brand", "conversion", "engagement", "funnel", "audience", "ROI", "growth"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Marketing", "Business", "Communications"],
  },
  {
    id: "growth-manager",
    name: "Growth Manager",
    category: "Business",
    required_skills: ["Growth Strategy", "A/B Testing", "Analytics", "User Acquisition", "Retention"],
    preferred_skills: ["SQL", "Python", "Product-Led Growth", "Paid Acquisition", "Viral Loops"],
    keywords: ["growth", "experimentation", "funnel optimization", "activation", "referral", "LTV"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Marketing", "Business", "CS"],
  },
  {
    id: "sales-manager",
    name: "Sales Manager",
    category: "Business",
    required_skills: ["Sales Strategy", "CRM", "Pipeline Management", "Negotiation", "Team Leadership"],
    preferred_skills: ["Salesforce", "HubSpot", "Account Management", "Forecasting"],
    keywords: ["revenue", "quota", "deal", "prospect", "close rate", "territory", "B2B"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Business", "Marketing"],
  },
  {
    id: "operations-manager",
    name: "Operations Manager",
    category: "Business",
    required_skills: ["Operations Management", "Process Improvement", "Budget Management", "Team Leadership"],
    preferred_skills: ["Lean", "Six Sigma", "Supply Chain", "ERP Systems", "Data Analysis"],
    keywords: ["efficiency", "optimization", "logistics", "vendor management", "SLA", "KPI"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Business", "Operations Management"],
  },
  // FINANCE
  {
    id: "financial-analyst",
    name: "Financial Analyst",
    category: "Finance",
    required_skills: ["Financial Modeling", "Excel", "Financial Reporting", "Valuation", "Budgeting"],
    preferred_skills: ["SQL", "Python", "Tableau", "SAP", "Bloomberg"],
    keywords: ["forecast", "P&L", "cash flow", "variance analysis", "financial statement", "ROI"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Finance", "Accounting", "CFA"],
  },
  {
    id: "auditor",
    name: "Auditor",
    category: "Finance",
    required_skills: ["Auditing Standards", "Risk Assessment", "Internal Controls", "Compliance", "Excel"],
    preferred_skills: ["SAP", "ACL", "IFRS", "SOX Compliance", "Data Analytics"],
    keywords: ["audit", "compliance", "risk", "control", "assurance", "regulation", "finding"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Accounting", "CPA", "CIA"],
  },
  {
    id: "risk-manager",
    name: "Risk Manager",
    category: "Finance",
    required_skills: ["Risk Assessment", "Compliance", "Financial Analysis", "Regulatory Frameworks"],
    preferred_skills: ["VaR", "Monte Carlo", "Basel III", "Stress Testing", "Python"],
    keywords: ["risk mitigation", "exposure", "regulatory", "framework", "portfolio risk"],
    minimum_years: 4,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Master's in Finance", "FRM", "CFA"],
  },
  {
    id: "investment-analyst",
    name: "Investment Analyst",
    category: "Finance",
    required_skills: ["Financial Modeling", "Valuation", "Research", "Excel", "Market Analysis"],
    preferred_skills: ["Bloomberg", "Python", "DCF", "Private Equity", "Venture Capital"],
    keywords: ["investment", "portfolio", "due diligence", "market research", "return", "equity"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Finance", "CFA", "MBA"],
  },
  {
    id: "accountant",
    name: "Accountant",
    category: "Finance",
    required_skills: ["GAAP", "Financial Reporting", "Tax Preparation", "Excel", "Bookkeeping"],
    preferred_skills: ["QuickBooks", "SAP", "ERP Systems", "Payroll", "Audit"],
    keywords: ["accounting", "journal entry", "reconciliation", "general ledger", "tax", "balance sheet"],
    minimum_years: 1,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Accounting", "CPA"],
  },
  {
    id: "tax-consultant",
    name: "Tax Consultant",
    category: "Finance",
    required_skills: ["Tax Law", "Tax Planning", "Compliance", "Financial Analysis", "Excel"],
    preferred_skills: ["International Tax", "Transfer Pricing", "Tax Software", "Research"],
    keywords: ["tax return", "deduction", "compliance", "IRS", "tax strategy", "filing"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Accounting", "JD", "CPA", "EA"],
  },
  // HR
  {
    id: "hr-specialist",
    name: "HR Specialist",
    category: "HR",
    required_skills: ["Recruitment", "Employee Relations", "HRIS", "Labor Law", "Onboarding"],
    preferred_skills: ["Workday", "SAP SuccessFactors", "Performance Management", "Compensation"],
    keywords: ["human resources", "employee", "benefits", "policy", "retention", "engagement"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in HR", "Business", "SHRM"],
  },
  {
    id: "technical-recruiter",
    name: "Technical Recruiter",
    category: "HR",
    required_skills: ["Technical Sourcing", "ATS", "Interviewing", "Pipeline Management", "Employer Branding"],
    preferred_skills: ["LinkedIn Recruiter", "Boolean Search", "Greenhouse", "Data-Driven Recruiting"],
    keywords: ["candidate", "sourcing", "talent pipeline", "offer", "hire", "screening", "tech stack"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in HR", "Business"],
  },
  {
    id: "talent-acquisition-manager",
    name: "Talent Acquisition Manager",
    category: "HR",
    required_skills: ["Recruitment Strategy", "Team Leadership", "ATS", "Employer Branding", "Metrics"],
    preferred_skills: ["Diversity Hiring", "Workforce Planning", "Executive Search", "Analytics"],
    keywords: ["talent strategy", "hiring", "recruitment", "cost-per-hire", "time-to-fill", "pipeline"],
    minimum_years: 5,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in HR", "MBA"],
  },
  {
    id: "hr-business-partner",
    name: "HR Business Partner",
    category: "HR",
    required_skills: ["Strategic HR", "Change Management", "Employee Relations", "Talent Development"],
    preferred_skills: ["Organizational Design", "Succession Planning", "Coaching", "Analytics"],
    keywords: ["business partner", "strategic", "organizational", "culture", "workforce", "leadership"],
    minimum_years: 5,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in HR", "MBA", "SHRM-SCP"],
  },
  // DESIGN
  {
    id: "ui-ux-designer",
    name: "UI/UX Designer",
    category: "Design",
    required_skills: ["Figma", "User Research", "Wireframing", "Prototyping", "Design Systems"],
    preferred_skills: ["Adobe XD", "Sketch", "Usability Testing", "Accessibility", "Motion Design"],
    keywords: ["user experience", "interface", "usability", "persona", "journey map", "interaction"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Design", "HCI", "Portfolio required"],
  },
  {
    id: "graphic-designer",
    name: "Graphic Designer",
    category: "Design",
    required_skills: ["Adobe Photoshop", "Illustrator", "Typography", "Color Theory", "Layout Design"],
    preferred_skills: ["After Effects", "InDesign", "Brand Identity", "Print Design", "3D"],
    keywords: ["visual design", "branding", "creative", "composition", "identity", "campaign"],
    minimum_years: 2,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Graphic Design", "Fine Arts", "Portfolio required"],
  },
  {
    id: "product-designer",
    name: "Product Designer",
    category: "Design",
    required_skills: ["Figma", "Product Thinking", "User Research", "Prototyping", "Design Systems"],
    preferred_skills: ["Data-Driven Design", "A/B Testing", "Frontend Development", "Accessibility"],
    keywords: ["end-to-end design", "product strategy", "user-centered", "iteration", "design sprint"],
    minimum_years: 3,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in Design", "HCI", "CS"],
  },
  {
    id: "content-writer",
    name: "Content Writer",
    category: "Design",
    required_skills: ["Content Writing", "SEO", "Copywriting", "Research", "Editing"],
    preferred_skills: ["Content Strategy", "CMS", "Social Media", "Technical Writing", "Analytics"],
    keywords: ["content", "engagement", "headline", "SEO", "audience", "brand voice", "copy"],
    minimum_years: 1,
    scoring_weights: { skills: 40, experience: 25, projects: 20, education: 10, impact_metrics: 5 },
    education_requirements: ["Bachelor's in English", "Communications", "Journalism"],
  },
];

export const JOB_ROLE_CATEGORIES = [...new Set(JOB_ROLES.map((r) => r.category))];

export function getJobRoleById(id: string): JobRole | undefined {
  return JOB_ROLES.find((r) => r.id === id);
}

export function getJobRolesByCategory(category: string): JobRole[] {
  return JOB_ROLES.filter((r) => r.category === category);
}
